박종범 lotto
BCSDLab-Edu/front_lotto_2024_2 pull request #1
Opened 2024-10-01 04:39 UTC by asa9874

# 로또 만들기

## 구현 방법
### 1-1.header,footer
    fixed 포지션으로 화면 상하단 고정
    ->@media를 사용하여화면 height: 855px 보다 작을시 relative
    로 포지션 변경
        
### 2.메인 컨텐츠
    flex박스로 중앙정렬, flex-direction: column;으로 세로로 정
    body에
    min-height: 855px;
    min-width: 414px;
    를 통해 메인컨텐츠 화면이 다 나올수있게함

#### 2-1. 구매금액 Form
    button 우측에 놓는 방법을 위해 position: absolute;
    right: 0; 이용

### 2-2 당첨번호 Form
    보너스 번호 우측 정렬을 위해 position: absolute;이용
    입력란 다음 방식으로 제한
```html
<input type="text" pattern="[0-9]" maxlength="1">
```

## 궁금한점
- maincontent를  flex-direction: column; 하여 내부의 가로로 정렬하고싶은 요소에서 어려움을 느껴 position absolute를 사용하게 되었는데 좀더 좋은 방법이 있었는지 궁금합니다.

2024-10-01 14:10 UTC, D0Dam requested changes
빠르게 제출을 해 주셨네요!
기본적으로 알고 충분히 알고 계신다고 생각이 들어서 좀 구체적으로 리뷰를 남겨 드렸습니다!
구현 방법과 궁금한점 써 주신 것도 좋아요!

### 구현 방법
- 1-1과 2, 2-2의 경우 왜 그렇게 구현했는지 다시 여쭈어 보고 싶네요..!

### 궁금한 점
> maincontent를 flex-direction: column; 하여 내부의 가로로 정렬하고싶은 요소에서 어려움을 느껴 position absolute를 사용하게 되었는데 좀더 좋은 방법이 있었는지 궁금합니다.

코드를 쭉 보면서 absolute를 사용한 요소에 대해서 리뷰를 남겨 두었어요! 한 번 확인해 보시고 이해가 잘 안된다면 다시 질문 주시면 좋을 것 같아요!

---

그리고 css의 flex와 grid를 공부해서 사용해 보시는 걸 추천 드립니다!
많은 부분들의 코드가 flex, grid를 포함하고 있었으면 좋겠어요!

리뷰 한 번 읽어 보시고 같이 코멘트로 대화하면서 좀 더 수정해봅시다! 수고하셨어요~!

2024-10-01 14:10 UTC, D0Dam commented on lotto.css
> +    padding: 0;
이런 css는 reset.css와 중복되네요!
사실 html, body에 reset.css 를 통해 한번 초기화를 해주었다면 저는 폰트를 주는 것 이외로 무언가 css를 주었던 적은 없었던 것 같아요.(모바일 뷰만 구현되어있는 경우 제외)
그래서 마찬가지로 html, body에 여러 스타일을 주셨는데, 이 스타일을 최대한 밑의 요소로 내려보는게 좋을 것 같습니다!
사실 지금과 같은 코드에서는 상관이 없어요! 다만 프로젝트를 하다보면 유지 보수하기에 상단에 많은 css가 걸려 있을수록 관리하기가 힘들어집니다. 여러 팀원들도 이를 모두 인지해야하는 불편함도 있구요! 그래서 좀 더 좋은 습관을 들인다는 느낌으로 알아주셨으면 좋겠습니다~!

2024-10-01 14:10 UTC, D0Dam commented on lotto.css
> +    position: fixed;
좋아요! sticky 도 줘 볼 수 있을 것 같은데, 어떤 부분에서 차이가 있을까요?

2024-10-01 14:10 UTC, D0Dam commented on lotto.css
> +}
absolute를 쓰지 않고서도 이렇게 쓰면 가능하겠네요!

```css
/* 헤더,푸터 */
header{
    position: fixed;
    display: flex;
    width: calc(100% - 260px);
    align-items: center;
    background-color: #4E5BA6;
    padding-inline: 130px;
    height: 64px;
    top: 0;
}

header > p{
    color: #fff;
}
```

추가적으로 `header p`와 `header > p`는 어떤 차이가 있을까요?

2024-10-01 14:10 UTC, D0Dam commented on lotto.css
> +    border: 1px solid;
위에만 주어도 될 것 같아요! 그리고 색도 넣어주면 더욱 좋겠네요!

```suggestion
    border-top: 1px solid #4E5BA633;  
```

2024-10-01 14:10 UTC, D0Dam commented on lotto.css
> +    height: 727px;
피그마 상의 수치대로 잘 해주셨어요!
반대로 이렇게 안하고 main-contents 안의 요소들에게 적절히 공통된 margin이나 padding을 주면 어떨까요?
이렇게 하게 된다면 어떤 장, 단점이 있을까요?

2024-10-01 14:10 UTC, D0Dam commented on lotto.css
> +    position: relative;
이 relative는 없어도 괜찮지 않을까요?

2024-10-01 14:10 UTC, D0Dam commented on lotto.css
> +    position: relative;
아 구입버튼에 영향을 주나 보네요..ㅎㅎ 그럴수록 이 relative가 잘 수정되어야겠다는 느낌을 받는군요~!

2024-10-01 14:10 UTC, D0Dam commented on lotto.css
> +    margin: 16px;
이걸 한번에 묶어서 쓸 수는 없을까요?

2024-10-01 14:10 UTC, D0Dam commented on lotto.css
> +.main-contents > * {
조금 과감한 코드라고 생각이 드네요..!

- 여기에서 과연 모든 main-contents 하위 요소가 border-radius가 있어야 할까요?
- main-contents 안의 요소들에게 margin가 같이 간격을 주는 대신 `display: flex, flex-direction: column, gap: 16px`을 사용해 볼 수 있을 것 같아요!

2024-10-01 14:10 UTC, D0Dam commented on lotto.css
> +    border: 1px solid #B4B4B4
```suggestion
    border: 1px solid #B4B4B4;
```

2024-10-01 14:10 UTC, D0Dam commented on lotto.css
> +    padding: 8px 8px;
이거와 동일한 것 같아요~!

```suggestion
    padding: 8px;
```

2024-10-01 14:10 UTC, D0Dam commented on lotto.css
> +    box-sizing: border-box;
box-sizing은 필요에 의해서 넣으신 건가요?

2024-10-01 14:10 UTC, D0Dam commented on lotto.css
> +    border: 1px solid #B4B4B4
이렇게 한번에 선언하시는 방식을 많이 사용한 것 같네요!
중복을 줄일 수 있으니 좋은 방법 같습니다!
하지만 그만큼 안에 들어갈 스타일 요소를 집중해서 고를 필요도 있을 것 같아요!
margin-right 같은 코드는 여기에서 공통으로 들어가면 다른 input에 영향을 줄 수 있을 것 같네요~!

![image](https://github.com/user-attachments/assets/e5d0829e-b53b-4181-84b3-37801931381a)

이 부분을 위해서 넣은 것 같은데 이 부분의 Input에만 적용을 하거나 gap을 사용하는 것이 바람직한 것 같습니다~!

2024-10-01 14:10 UTC, D0Dam commented on lotto.css
> +    height: 64px;
이렇게 영역을 잡아놓았지만 영역안에 요소를 다 넣지는 못했어요..

![image](https://github.com/user-attachments/assets/ea93a29c-5b86-4df9-92fa-b8909596444c)

이렇게 된다면 오히려 혼란만 불러올 뿐이겠죠?
피그마에서 px을 무조건 맞추어 쓸 필요는 없어요! 오히려 화면에 따라 능동적으로 변하게 하는 것이 오히려 나을 수도 있습니다!
물론 능동적으로 변해도 같은 화면에서는 같은 px을 유지하게끔 해야겠지만요!

2024-10-01 14:10 UTC, D0Dam commented on lotto.css
> +    height: 64px;
이렇게 된 원인을 한가지 꼽아보자면 p 태그를 썻다는 부분이겠네요! p태그가 기본적으로 어떤 css를 갖는지 찾아보면 알게 될 거에요~!

2024-10-01 14:10 UTC, D0Dam commented on lotto.css
> +}
이렇게 해도 구입 버튼과 input의 align이 맞지 않는 것은 사진과 같이 영역을 잡아놓은 것과 연관이 있습니다!

![image](https://github.com/user-attachments/assets/94ba7b0f-375b-4276-8bda-169d06505c0a)

2024-10-01 14:10 UTC, D0Dam commented on lotto.css
> +}
위에서 쭉 보면서 느낀건, margin으로 간격을 만들고, absolute, p 태그를 많이 활용을 하는 것 같아요.
CSS의 flex를많이 활용해 보았으면 좋겠어요. 지금 ui를 보면 이렇게 밀려있단 말이죠?

![image](https://github.com/user-attachments/assets/463ce1f8-8a5b-48df-bf83-7433811f53e9)

이건 p 태그 때문에 생겨난 문제인데 이 문제는 위에서도 한 번 언급했다시피 해결 방법을 찾아보았으면 좋겠어요!

flex를 활용한다면 어떤 형식으로 짤 수 있는지 살펴보면 이 정도가 되겠네요!

```suggestion
.winning-lotto-form{
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.number-input-container{
  display: flex;
  justify-content: space-between;
}

.number-input-container input{
  width: 36px;
}

.winning, .bonus {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.bonus {
  align-items: flex-end;
}

```

2024-10-01 14:10 UTC, D0Dam commented on lotto.css
> +}
잘 구분해서 나눠주셨네요!👍

2024-10-01 14:10 UTC, D0Dam commented on lotto.css
> +}
이게 EOL이라는 건데 있으면 안좋아요. 한번 찾아보고 없애보면 좋을 것 같아요~!

2024-10-01 14:10 UTC, D0Dam commented on lotto.css
> +}
여기서 이 반응형이 왜 필요한걸가요? 제 생각에는 없어도 될 것 같은데 말이죠..?

2024-10-01 14:10 UTC, D0Dam commented on lotto.html
> +<html lang="ko">
👍

2024-10-01 14:10 UTC, D0Dam commented on lotto.html
> +        <p class="title">🎱 000 로또</p>
ㅋㅋㅋㅋ 여기 원래 본인 이름 쓰는 겁니다. ㅎㅎ
p태그 보다는 다른 태그를 쓰는게 제 생각에는 더 좋지 않을까 싶은데요.. p태그를 밑에서도 많이 사용하셔서 말씀드리자면 언제 p태그를 주로 사용하는지 찾아본다면 도움이 되실 것 같아요~!

2024-10-01 14:10 UTC, D0Dam commented on lotto.html
> +        <form class="purchase-form">
form 좋아요~~!

2024-10-01 14:10 UTC, D0Dam commented on lotto.html
> +                        <input type="text" pattern="[0-9]" maxlength="1">
input type number는 어떨까요?

2024-10-01 14:10 UTC, D0Dam commented on reset.css
reset.css를 가져올 줄은 몰랐네요..ㅎㅎㅋㅋㅋㅋ(좋은 의미)

2024-10-01 15:15 UTC, asa9874 commented on lotto.css
> +}
```header p```는 header의 모든 내부 요소 p들에게 적용되고 
```header > p```는 바로아래 자식인 p들에게만 적용될것같네요

2024-10-01 15:15 UTC, asa9874 commented on lotto.css
> +}
header p는 header의 모든 내부 요소 p들에게 적용되고
header > p는 바로아래 자식인 p들에게만 적용될것같네요

2024-10-01 15:20 UTC, asa9874 commented on lotto.html
> +        <p class="title">🎱 000 로또</p>
```<p>``` 는 문단을 만드는 태그니까 지금처럼  텍스트요소를  감쌀때는  ```<span>```  태그를 사용하는게 좋나요?

2024-10-01 15:42 UTC, asa9874 commented on lotto.css
> +    position: fixed;
```position: sticky``` 를 활용하면 해당 범위 밖으로는 나갈떄는 header랑 footer가 따라오지않게 될것같네요

혹시 ```position: fixed```를 사용하는 것보다 ```position: sticky``` 를 사용할때 얻는 이점들이 있을까요?

2024-10-01 15:52 UTC, asa9874 commented on lotto.css
> +    height: 727px;
공통된 margin이나 padding을 주면 일관성있게 유지보수하기 편해지는 대신 내부에서 특정한 디자인을 해야할때 공통된 margin, padding 을 고려해서 작성해야할것 같아요

2024-10-01 16:05 UTC, asa9874 commented on lotto.css
> +    box-sizing: border-box;
heigh , width가 원하는대로 input 상자 크기로 되지않았는데 padding을 고려하지않았었네요. padding 하고 크기를 조절하는 대신 box-sizing을 제거할려고합니다.

2024-10-02 02:09 UTC, D0Dam commented on lotto.css
> +    position: fixed;
> position: sticky 를 활용하면 해당 범위 밖으로는 나갈떄는 header랑 footer가 따라오지않게 될것같네요

정확히 이야기 하면 따라오게 할수도, 따라오지 않게 할수도 있게 된다고 하는게 올바른 표현 같아요!

사용처가 다르다고 이야기 하고 싶네요..!
header 같은 경우에는 여러 회사마다 갈리기는 합니다!
차이라고 하면 완전 고정이 되어 있느냐 그래도 스크롤의 유동성을 따라가느냐가 될 수 있을 것 같네요!

https://www.daangn.com/
https://ohou.se/

이 두 사이트를 비교해보면 한 곳은 fixed를 쓰고, 한 곳은 sticky를 사용하고 있습니다! 
스크롤 해서 보시면 어느정도 차이점을 육안으로도 느끼실 수 있을거에요!

2024-10-02 02:18 UTC, D0Dam commented on lotto.html
> +        <p class="title">🎱 000 로또</p>
저라면.. 그럴 것 같습니다!
사실 대체적으로 대부분의 사이트는 svg가 그 자리를 대체하게 될 테지만요 ㅎㅎ

2024-10-02 14:19 UTC, asa9874 commented
수정완료했습니다

2024-10-31 08:44 UTC, D0Dam requested changes
역시 가장 빠르게 내 주셨네요!
이번에 종범님의 코드를 보고 혼자 많이 써보았다는 느낌을 많이 받았어요!
코드가 굉장히 러프한데 그렇다고 꼬투리를 잡을만한 로직은 별로 없는 것 같네요!

하지만 앞으로 코드는 혼자서만이 아닌, 많은 사람들이 공유하면서 다같이 협업하면서 쌓아나가게 될거에요. 이에 요구되는 여러 부분이 있는데 이 부분들을 좀 채워보았으면 좋겠어요.

넓은 범주로 뽑아보면
1. 코드 통일성, 규칙성(format 부분)
  - 개행, 간격, 중괄호 사용법과 일종의 컨벤션(ex. airbnb code convention, lint 등), textCase(camelCase, snake_case 등)
3. 네이밍
  - 이건 언급을 많이 했기도하고 어느정도 신경 써 주신 것 같네요..!
5. 코드 분리
  - 공통로직 분리(util스러운 함수라도)와 callback 분리
7. 구조화
  - 폴더와 파일을 나눠 validation, view, event, process, constant 등 기준에 맞게 구조화

정도를 해보면 좋을 것 같네요!
종범님은 사실 구현이 빠르시니 이런 협업 관점이나 코드 퀄리티, Error case, Edge case 대응 부분을 많이 생각하면서 만들어보셨으면 좋겠어요! 수고하셨습니다!

2024-10-31 08:44 UTC, D0Dam commented on main.js
> +    })
여기 callback들을 좀 더 읽기 좋게 만들어 볼 수는 없을까요?

2024-10-31 08:44 UTC, D0Dam commented on main.js
> +let lottos=[]                   //구입로또리스트
이거 포함해서 아래에 세미콜론이 빠져있는 곳이 꽤 있네요..!

```suggestion
let lottos=[];                   //구입로또리스트
```

2024-10-31 08:44 UTC, D0Dam commented on main.js
> +        if(!lottoNumbers.includes(num)){lottoNumbers.push(num);}
이런 코드와 같이 띄어쓰기나 개행, 중괄호 사용법 등 다채롭게 코드에서 나타나고 있는 것 같아요!
어느정도 자신만의 기준을 세워 코드 전반적으로 통일성을 줘보면 어떨까요?

2025-08-01 15:36 UTC, closed without merging