강성훈 1주차 과제 제출합니다.
BCSDLab-Edu/front_lotto_2024_2 pull request #4
Opened 2024-10-02 07:39 UTC by kang-s-h

1. 구역 분할 : header , section , footer 로 body에 구역을 나누어 작업 하기 편하게 하였습니다.
2. header,footer : 최상단과 최하단에 붙어있기 때문에 fixed로 고정하여 작업하였습니다.
3. section : 모든 것을 fixed로 고정하는 것 보다 section 안에 자식 요소들이 section을 기준으로 정렬 하는 것이 효율적이기에 relative와 absolute를 사용하여 좀 더 효율적으로 코딩하였습니다.

2024-10-02 08:08 UTC, junghaesung79 reviewed
수고하셨어요!

2024-10-02 08:25 UTC, junghaesung79 commented on lotto/_1W.css
> +  display: flex;
블록 사이에 공백을 두어 구분하기 쉽게 하는 컨벤션이 있어요! 아직 적용할 필요는 없지만 있다는 것만 알아두시면 좋을 것 같아요~

2024-10-02 08:25 UTC, junghaesung79 commented on lotto/_1W.css
> +  margin-left: 2%;
또 컨벤션 이야기인데 html/css에서는 케밥 케이스를 가장 많이 사용한답니다.

2024-10-02 08:25 UTC, junghaesung79 commented on lotto/_1W.html
> +        <div></div>
이 빈 태그는 어떤 의도인가요?

2024-10-02 08:41 UTC, kang-s-h commented on lotto/_1W.css
> +  margin-left: 2%;
아하 수정하겠습니다.

2024-10-02 08:42 UTC, kang-s-h commented on lotto/_1W.css
> +  display: flex;
수정하겠습니다.

2024-10-02 08:45 UTC, kang-s-h commented on lotto/_1W.html
> +        <div></div>
이건 틀 짜다가 잘못 만들었는데 못 지운것 같습니다. 수정하겠습니다.

2024-10-02 13:38 UTC, D0Dam requested changes
수고하셨습니다!
리뷰 한 번 읽어보시고 flex, grid에 익숙해지셨으면 합니다!
이번 1주차 교육의 목표를 이야기하자면

1. flex, grid 잘 써보기
2. 여러 태그를 사용해보기
3. 여러 태그에 있는 속성들을 사용해보기

정도인데요!
예를 들어보자면 input에 어떤 속성이 있는지 알아보거나 form태그를 사용해볼 수 없을까? 와 같은 생각이 뻗어나갔으면 합니다~!

2024-10-02 13:38 UTC, D0Dam commented on lotto/img/볼링공.png
사실 이 볼링공과 입장권은 이모지랍니다..ㅎㅎ
그냥 텍스트처럼 넣을 수 있어요.(물론 이렇게 이미지를 넣는 경험은 값지다고 생각합니다!)

2024-10-02 13:38 UTC, D0Dam commented on lotto/_1W.css
> +  overflow: hidden;
`overflow: hidden` 은 필요에 의해서 넣게 되었나요?
없이는 힘들까요?

2024-10-02 13:38 UTC, D0Dam commented on lotto/_1W.css
> +  height: 6%;
%를 많이 사용해서 이것도 대표해서 리뷰 하나 남겨볼게요~!
width는 %를 많이 사용하긴 합니다!

하지만 이렇게 높이를 %로 주게 되면 문제가 생길 수도 있는데요.
모바일, 데스크탑과 os별, 플랫폼별 여러 기기들은 이 %단위를 각자 다 다르게 인식한답니다?
이 %느낌을 살리고 싶다면 vh 를 쓰면 되겠지만 저는 그냥 px을 추천해 드리고 싶네요!

번외 ) rem, em 개념을 아신다면 이걸 사용해도 좋습니다~!

2024-10-02 13:38 UTC, D0Dam commented on lotto/_1W.css
전체적으로 fixed와 absolute를 사용해 주셨네요!
이렇게 하면 지금은 문제가 없어보이지만 나중에 가서 유지 보수하기 많이 어려워지고 반응형 대응이 어려워지게 됩니다!
스크롤링 문제나 봇이 해당 html을 파악할 때 요소 우선순위 파악이 잘못될수도 있죠.

그러니 웬만하면 flex, grid를 활용해서 css를 짜는 보는 습관을 만들기를 바랍니다!

2024-10-02 13:38 UTC, D0Dam commented on lotto/_1W.html
> +    <script src="_1W.js"></script>
defer 속성도 알아보면 좋을 것 같아요~!

2024-10-02 13:38 UTC, D0Dam commented on lotto/_1W.html
> +        <img src="img/볼링공.png" alt="" class="ball" />
alt가 비어있기보다는 속성을 사용한다면 무엇인가 적어주었으면 좋겠군요?

2024-10-02 13:38 UTC, D0Dam commented on lotto/_1W.html
> +<html lang="en">
여기서 lang이 en이면 어떤 점에서 문제가 생길까요?

2024-10-02 13:43 UTC, D0Dam commented
여기 브랜치를 main에서 내보내고 있는데 본인의 레포에서는 본인 이름의 브랜치에서 내보내 주세요!
<img width="726" alt="image" src="https://github.com/user-attachments/assets/2c0c242e-5faa-472e-a64e-b14c59ebb8e7">

2024-10-03 04:13 UTC, kang-s-h commented on lotto/img/볼링공.png
아하..ㅎㅎ 모든 피드백 참고하여 최대한 빨리 고치겠습니다!

2024-10-04 14:12 UTC, closed without merging